version : '3'
services:
  web:
    container_name: chrome-extension-recommend-api
    image: rhlehfndvkd7558/recommend-api
    restart : always
    ports:
      - "8000:8000"

    build:
      dockerfile: Dockerfile
      context: .